mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: omeka
    MYSQL_DATABASE: omeka
    MYSQL_USER: omeka
    MYSQL_PASSWORD: omeka

postfix:
  image: ccnmtl/postfix

omeka:
  image: enlore/fog-omeka:latest
  ports:
    - "8080:80"
  links:
    - mysql
    - postfix
  environment:
    MYSQL_DBNAME: omeka
    MYSQL_USER: omeka
    MYSQL_PASSWORD: omeka
    #PHP_IDE_CONFIG: "serverName=omekadocker_omeka_1_xdebug_server"
  volumes:
    - ./src:/app/themes/curatescape
